### ISSUE TITLE
Water Diagnostics Manual Entry: Error message when trying to submit entries leads to duplicate entries 

### ISSUE THREAD

**Issue by elaineHaiti** [dloHaiti/remote-monitoring-system#2]
- I received this error yesterday when trying to submit manual entry readings: erreur lors de l'envoi des 1 mesure ou 0 des ventes ou 0 des livraisons au serveur.  I checked the database and my readings were not there.  I went back and re-entered everything again.  When I hit submit, both sets of readings were sent to the server.  Is this expected?  Should I tell users that if they see that error to just assume the readings will go through next time?

Not expected. It sounds like a temporary network error, and it's always worth trying to send it again manually before re-entering it.

**Comment by sghill** [comment]
> it's always worth trying to send it again manually before re-entering it.

I think this is a reasonable manual solution unless we can identify a pattern when this occurs. Should we close and revisit in the future?

**Comment by sghill** [comment]
Closing with manual fix stated above. Any reoccurrence should open a new issue.
