### ISSUE TITLE
Water Diagnostics Manual Entry: customize order for entering data

### ISSUE THREAD

**Issue by elaineHaiti** [dloHaiti/remote-monitoring-system#3]
Order of Entry:
- I know we discussed having the manual entry screens go in alphabetical order.  Is there any way that I can add an order column or something to the parameter table to have them sort that way instead? 

It's not super quick, but definitely do-able. Also requires a re-deploy and some extra database management testing up front (since this would be the first database migration)

**Comment by sghill** [comment]
SamplingSites have many Parameters in today's world. We could fix this in a few different ways, depending on what exactly we're after (arranged by difficulty):
1. Rename the Parameters to take advantage of the current naming. Requires only a database change.
2. Make the OK/NOT OK measurements always appear first or last. Only the Android app would need to be changed.
3. Give each Parameter a global priority. Assigning 1 to a Parameter would make it first in every SamplingSite it belongs to, assigning something like 9999 would make it last.
4. Give each Parameter a priority relative to its SamplingSites. This gives the most control, but is significantly more difficult to maintain. Every single relationship needs a priority.

**Comment by elaineHaiti** [comment]
Options 1 and 2 don't really work for what we need.  Option 3 will probably be the best choice at this point

**Comment by sghill** [comment]
Closing with 30-Aug-2013 deployment
